import type { TokenSource, ThemeDef } from "./types.js";

const j = (v: unknown) => JSON.stringify(v);

function paletteBlock(src: TokenSource): string {
  const entries = Object.entries(src.primitive.color).map(([k, v]) => `  ${j(k)}: ${j(v)},`);
  return `const palette = {\n${entries.join("\n")}\n};`;
}

function themeBlock(src: TokenSource, theme: ThemeDef): string {
  const colors = Object.entries(theme.semantic.color)
    .map(([name, ref]) => `    ${j(name)}: palette.${ref},`)
    .join("\n");
  const spacing = Object.entries(src.primitive.space)
    .map(([k, v]) => `    ${j(k)}: ${v},`)
    .join("\n");
  const radii = Object.entries(src.primitive.radius)
    .map(([k, v]) => `    ${j(k)}: ${v},`)
    .join("\n");
  const textVariants = Object.entries(theme.semantic.text)
    .map(([name, tv]) => {
      return `    ${j(name)}: { fontFamily: ${j(src.primitive.fontFamily[tv.fontFamily])}, fontSize: ${src.primitive.fontSize[tv.fontSize]}, lineHeight: ${Math.round(src.primitive.fontSize[tv.fontSize] * src.primitive.lineHeight[tv.lineHeight])}, fontWeight: ${j(String(src.primitive.fontWeight[tv.fontWeight]))} },`;
    })
    .join("\n");
  return `export const ${theme.name}Theme = createTheme({
  colors: {
${colors}
  },
  spacing: {
${spacing}
  },
  borderRadii: {
${radii}
  },
  textVariants: {
${textVariants}
  },
});`;
}

export function generateRestyleTheme(src: TokenSource): string {
  const header = `// AUTO-GENERATED by huggable tokens-codegen. Do not edit by hand.
import { createTheme } from "@shopify/restyle";

${paletteBlock(src)}`;
  const themes = src.themes.map((t) => themeBlock(src, t)).join("\n\n");
  const first = src.themes[0].name;
  const footer = `export const defaultTheme = ${first}Theme;
export type Theme = typeof ${first}Theme;`;
  return [header, themes, footer].join("\n\n") + "\n";
}
