import type { TokenSource, ThemeDef } from "./types.js";

const j = (v: unknown) => JSON.stringify(v);

export function toVarKey(roleName: string): string {
  return roleName
    .split(".")
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

function resolvedColors(src: TokenSource, theme: ThemeDef): Array<[string, string]> {
  return Object.entries(theme.semantic.color).map(([name, ref]) => [toVarKey(name), src.primitive.color[ref]]);
}

export function generateStylexVars(src: TokenSource): string {
  const [base, ...rest] = src.themes;
  const defaults = resolvedColors(src, base)
    .map(([k, v]) => `  ${k}: ${j(v)},`)
    .join("\n");

  const spacing = Object.entries(src.primitive.space)
    .map(([k, v]) => `  space${k}: "${v}px",`)
    .join("\n");

  const overrides = rest
    .map((theme) => {
      const body = resolvedColors(src, theme)
        .map(([k, v]) => `  ${k}: ${j(v)},`)
        .join("\n");
      return `export const ${theme.name}Theme = stylex.createTheme(colors, {\n${body}\n});`;
    })
    .join("\n\n");

  return `// AUTO-GENERATED by huggable tokens-codegen. Do not edit by hand.
import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
${defaults}
});

export const spacing = stylex.defineVars({
${spacing}
});

${overrides}
`;
}
